CREATE TABLE TOUR_ENTITY (tripId VARCHAR(50),
tripFrom VARCHAR(50), tripTo VARCHAR(50), days INT, tripFare INT, headCount INT , PRIMARY KEY (tripId));

DESCRIBE TOUR_ENTITY;

SELECT * FROM TOUR_ENTITY;

INSERT INTO TOUR_ENTITY VALUES ('INDSING5C', 'Bangalore', 'Chennai', 3, 2500, 6);