CREATE TABLE plantinheritance (plantName VARCHAR(50) NOT NULL, kind VARCHAR(50), flowerColor VARCHAR(50), usefulPart VARCHAR(50), PRIMARY KEY (plantName));

#################################################################################

CREATE TABLE PLANT_JOINED (plantName VARCHAR(50) NOT NULL PRIMARY KEY, kind VARCHAR(50));

CREATE TABLE MEDICINE_PLANT_JOINED (plantName VARCHAR(50), usefulPart VARCHAR(50),
CONSTRAINT MedicinePlant_FK FOREIGN KEY (plantName) REFERENCES PLANT_JOINED (plantName));

CREATE TABLE ORNAMENTAL_PLANT_JOINED (plantName VARCHAR(50), flowerColor VARCHAR(50),
CONSTRAINT OrnamentalPlant_FK FOREIGN KEY (plantName) REFERENCES PLANT_JOINED (plantName));

SELECT * FROM PLANT_JOINED; SELECT * FROM MEDICINE_PLANT_JOINED; SELECT * FROM ORNAMENTAL_PLANT_JOINED;

drop table MEDICINE_PLANT_JOINED; drop table ORNAMENTAL_PLANT_JOINED;drop table PLANT_JOINED;

describe MEDICINE_PLANT_JOINED; describe ORNAMENTAL_PLANT_JOINED; describe PLANT_JOINED;

###################################################################################

CREATE TABLE PLANT_TABLEPERCLASS (plantName VARCHAR(50) NOT NULL PRIMARY KEY, kind VARCHAR(50));

CREATE TABLE MEDICINE_PLANT_TABLEPERCLASS (plantName VARCHAR(50) NOT NULL, kind VARCHAR(50), usefulPart VARCHAR(50));

CREATE TABLE ORNAMENTAL_PLANT_TABLEPERCLASS (plantName VARCHAR(50) NOT NULL, kind VARCHAR(50), flowerColor VARCHAR(50));


SELECT * FROM PLANT_TABLEPERCLASS; SELECT * FROM MEDICINE_PLANT_TABLEPERCLASS; SELECT * FROM ORNAMENTAL_PLANT_TABLEPERCLASS;

drop table MEDICINE_PLANT_TABLEPERCLASS; drop table ORNAMENTAL_PLANT_TABLEPERCLASS;drop table PLANT_TABLEPERCLASS;

describe MEDICINE_PLANT_TABLEPERCLASS; describe ORNAMENTAL_PLANT_TABLEPERCLASS; describe PLANT_TABLEPERCLASS;

####################################################################################