CREATE TABLE MOVIES_CRITERIA (movieId VARCHAR(50), movieName VARCHAR(50), language VARCHAR(50), releasedIn INT, revenueInDollars INT, PRIMARY KEY (movieId));
DESCRIBE MOVIES_CRITERIA;
SELECT * FROM MOVIES_CRITERIA;