CREATE TABLE CUSTOMER_ENVER (customerId INT, name VARCHAR(50),
dob DATE, emailId VARCHAR(50), PRIMARY KEY(customerId));

CREATE TABLE REVINFO (REV INT PRIMARY KEY AUTO_INCREMENT, REVSTAMP LONG);

CREATE TABLE CUSTOMER_ENVER_AUD (customerId INT, REV INT, REVTYPE INT,
name VARCHAR(50), dob DATE, emailId VARCHAR(50));

DESCRIBE CUSTOMER_ENVER;DESCRIBE REVINFO; DESCRIBE CUSTOMER_ENVER_AUD;


SELECT * FROM CUSTOMER_ENVER; SELECT * FROM REVINFO; SELECT * FROM CUSTOMER_ENVER_AUD;

###################################################################################

ALTER TABLE REVINFO MODIFY COLUMN REV NOT NULL AUTO_INCREMENT;



